---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[sc::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      sc:
        server:
          api_user: 'YOUR_USER_NAME_HERE'
          api_key: 'YOUR_API_KEY_HERE'
          cmd_options: [
                '--se-port "%i"',
                '--logfile -',
                '--pidfile "/tmp/sc_%i.pid"',
                '--no-remove-colliding-tunnels'
              ]
